<a href="https://colab.research.google.com/github/Sim-mi-gyeong/DeepLearning/blob/main/pytorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tensor(텐서): 배열이나 행렬과 유사한 특수한 자료구조 -> 모델의 입력과 출력, 모델의 매개변수를 부호화(encode)

In [ ]:
import torch
import numpy as np

In [ ]:
# 텐서 초기화

# 데이터로부터 직접 생성하기 - 데이터의 자료형은 자동으로 유추
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
# Numpy 배열로부터 생성하기
np_array = np.array(data)
print(np_array)

x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
# 다른 텐서로부터 생성하기 
# - 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype)을 유지)

x_ones = torch.ones_like(x_data)  # x_data의 속성 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8615, 0.8647],
        [0.0976, 0.9069]]) 



In [ ]:
# 무작위(random) 또는 상수(constant) 값을 사용하기
# shape: 텐서의 차원(dimension)을 나타내는 튜플(tuple)

shape = (2,3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n ")
print(f"Ones Tensor : \n {ones_tensor} \n ")
print(f"Zeros Tensor : \n {zeros_tensor} ")

Random Tensor : 
 tensor([[0.7391, 0.7225, 0.8262],
        [0.3639, 0.3838, 0.7582]]) 
 
Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 
Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


In [ ]:
# 텐서의 속성(Attribute)

tensor = torch.rand(3,4)

print(f"Shape of tensor : {tensor.shape} \n ")
print(f"Datatype of tensor : {tensor.dtype} \n ")
print(f"Device tensor is sorted on : {tensor.device}")

Shape of tensor : torch.Size([3, 4]) 
 
Datatype of tensor : torch.float32 
 
Device tensor is sorted on : cpu


In [ ]:
# 텐서의 연산(Operation)

# 기본적으로 텐서는 CPU에 생성
# .to 메서드를 사용하면 GPU의 가용성을 확인한 뒤 GPU로 텐서를 명시적으로 이동 가능

if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [ ]:
# Numpy식의 표준 인덱싱과 슬라이싱

tensor = torch.ones(4,4)
print('Frist row : ', tensor[0])
print('First column : ', tensor[ : , 0])
print('Last column : ', tensor[..., -1])

tensor[:, 1] = 0 
print(tensor)

Frist row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 텐서 합치기: torch.cat을 사용해 주어진 차원에 따라 일련의 텐서 연결 가능
# torch.stack(tensors, dim=0, *, out=None): 텐서 결합 

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# 산술 연산(Arithmetic operations)

# matrix multiplication -> y1 = y2 = y3
y1 = tensor @ tensor.T
print('y1 : \n', y1)
y2 = tensor.matmul(tensor.T)
print('y2 : \n', y2)
y3 = torch.rand_like(tensor)
print('y3 : \n', y3)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱(element-wise product) 계산 -> z1 = z2 = z3
z1 = tensor * tensor
print('z1 : \n', z1)
z2 = tensor.mul(tensor)
print('z2 : \n ', z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

y1 : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 : 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 : 
 tensor([[0.4357, 0.7821, 0.7815, 0.6302],
        [0.6121, 0.1605, 0.6161, 0.2735],
        [0.3536, 0.2037, 0.1896, 0.4551],
        [0.9414, 0.1229, 0.2324, 0.8137]])
z1 : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2 : 
  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
print(torch.matmul(tensor, tensor.T, out=y3))

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
# 단일 요소(single-element) 텐서: 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우 -> .item()을 사용하여 Python 숫자 값으로 변환 가능
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
# 바꿔치기(in-place) 연산: 연산 결과를 피연산자(operand)에 저장하는 연산
# 접미사 '_' / ex) x.copy_(y) 나 x.t_() 는 x 를 변경

print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
# NumPy 변환(Bridge)
# CPU상의 텐서와 Numpy 배열은 메모리공간 공유 -> 하나 변경 시 다른 하나도 변경

# 텐서를 Numpy 배열로 변환하기
t=torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [ ]:
# 텐서의 변경 사항이 NumPy 배열에 반영
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


In [ ]:
# Numpy 배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
# NumPy 배열의 변경 사항이 텐서에 반영
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
